name: farmseasy_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Network
  dio: ^5.9.0

  # Routing
  go_router: ^17.0.0

  # Image Picker
  image_picker: ^1.2.1

  # Permissions
  permission_handler: ^12.0.1

  # Notifications
  flutter_local_notifications: ^19.5.0

  # JSON
  json_annotation: ^4.9.0

  provider: ^6.1.2

  # Fonts
  google_fonts: ^6.3.2

  # Shared Preferences
  shared_preferences: ^2.1.1
  intl: ^0.20.2

  # Animations
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4  # For generating app launcher icon

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icons/
    - assets/icons/final_logo.png
    - assets/illustrations/farmer_illustration.png
    - assets/images/farm_bg.jpg
    - assets/images/bg_images/bg_image1.jpg
    - assets/images/bg_images/bg_image2.jpg
    - assets/images/bg_images/bg_image3.jpg
    - assets/images/bg_images/bg_image4.jpg
    - assets/images/bg_images/bg_image5.jpg
    - assets/images/bg_images/bg_image6.jpg
    - assets/images/bg_images/bg_image7.jpg
    - assets/images/bg_images/bg_image8.jpg
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/final_logo.png"
