version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Moving into Frontend directory"
      - cd Frontend
      - echo "Installing frontend dependencies"
      - if [ -f package-lock.json ]; then npm ci; else npm install; fi

  build:
    commands:
      - echo "Building frontend using Vite"
      - npm run build

artifacts:
  base-directory: Frontend/dist
  files:
    - '**/*'

cache:
  paths:
    - Frontend/node_modules/**/*
