version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Moving into backend directory"
      - cd backend
      - npm install

  build:
    commands:
      - echo "Backend CI completed successfully"

artifacts:
  base-directory: backend
  files:
    - '**/*'

cache:
  paths:
    - backend/node_modules/**/*
