# -*- coding: utf-8 -*-
"""Wheat_Master_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXz8YD_RKiu2Vocnxu6bkIELpmCIrS8R
"""

import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error

DATA_PATH = "/content/Wheat_Master_Data.xlsx"
df = pd.read_excel(DATA_PATH)

crop_encoder = LabelEncoder()
stage_encoder = LabelEncoder()

df["crop_enc"] = crop_encoder.fit_transform(df["crop"])
df["stage_enc"] = stage_encoder.fit_transform(df["growth_stage"])

FEATURE_COLUMNS = [
    "vegetation_stress_score",
    "water_stress_score",
    "soil_stress_score",
    "final_stress_percent",
    "gdd_min",
    "gdd_max",
    "crop_enc",
    "stage_enc"
]

X = df[FEATURE_COLUMNS]

TARGET_COLUMNS = [
    "yellow_rust",
    "brown_rust",
    "fusarium_head_blight",
    "powdery_mildew",
    "leaf_blight",
    "root_rot",
    "smut"
]

y = df[TARGET_COLUMNS]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ann_model = MLPRegressor(
    hidden_layer_sizes=(32, 16),
    activation="relu",
    solver="adam",
    max_iter=1200,
    random_state=42
)

ann_model.fit(X_train_scaled, y_train)

y_pred = ann_model.predict(X_test_scaled)
mae = mean_absolute_error(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.4f}")

with open("disease_probability_ann_multi.pkl", "wb") as f:
    pickle.dump(ann_model, f)

with open("stress_scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("crop_encoder.pkl", "wb") as f:
    pickle.dump(crop_encoder, f)

with open("stage_encoder.pkl", "wb") as f:
    pickle.dump(stage_encoder, f)

print("✅ Training complete. Multi-disease ANN model saved.")