version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Moving into backend directory"
      - cd backend
      - echo "Installing backend dependencies"
      - npm ci

  build:
    commands:
      - echo "Backend build step(no compile required)"
      - echo "CI passed for backend"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - backend/node_modules/**/*
